#! /usr/bin/expect -f
set timeout 100
set username [lindex $argv 0]
set ip [lindex $argv 1]   
set password [lindex $argv 2]   
set cmd [lindex $argv 3]
spawn ssh $username@$ip
expect {
    "yes/no" {send "yes\r"} 
    "*assword:" {send "$password\r"}
}
expect "*#*" { send "$cmd\r" }
expect "*#*" { send "exit\r" }
#expect "]*"         
#send "consul agent -config-dir /etc/consul.d/ &\r"
#send "$cmd\r"
#send "exit\r"
expect eof
#exit
