#!/usr/bin/expect -f
set timeout 100
set username [lindex $argv 0]
set ip [lindex $argv 1]
set password [lindex $argv 2]
set logdir [lindex $argv 3]
set facility [lindex $argv 4]
spawn ssh $username@$ip
expect {
	"*yes/no" { send "yes\r"; exp_continue}
	"*password:" { send "$password\r" }
}
expect "*#*" { send "echo \"$facility.*                                                $logdir\" >>/etc/rsyslog.conf\r" }
expect "*#*" { send "service rsyslog restart\r" }
expect "*#*" { send "exit\r" }

