package main

const (
	triggered        = "001"
	consulapi_failed = "002"
	give_async_repl  = "003"
	//	completed = "004"
	consulapi_success                   = "005"
	peer_service_health_failed          = "006"
	peer_service_health_success         = "007"
	service_noexist                     = "008"
	service_exist                       = "009"
	service_passing                     = "010"
	repl_err_service_warning            = "011"
	switch_async                        = "012"
	switch_async_format_err             = "013"
	service_critical                    = "014"
	set_counter_failed                  = "015"
	set_counter_success                 = "016"
	service_invalid                     = "017"
	get_leader_failed                   = "018"
	get_leader_success                  = "019"
	no_leader                           = "020"
	is_leader                           = "021"
	get_service_status_failed           = "022"
	get_service_status_success          = "023"
	service_status                      = "024"
	create_database_object_failed       = "025"
	create_database_object_success      = "026"
	connected_database_failed           = "027"
	connected_database_success          = "028"
	set_keepsyncrepl_failed             = "029"
	set_keepsyncrepl_success            = "030"
	set_trysyncrepl_failed              = "031"
	set_trysyncrepl_success             = "032"
	switch_local_async_repl             = "033"
	handlers_sleep                      = "034"
	connecting_database                 = "035"
	create_peer_database_object_failed  = "036"
	create_peer_database_object_success = "037"
	connected_peer_database_failed      = "038"
	connected_peer_database_success     = "039"
	check_perr_dabases_io_failed        = "040"
	check_perr_dabases_io_success       = "041"
	resolve_slave_status_failed         = "042"
	io_status                           = "043"
)
